spring:
  datasource:
    url: jdbc:mysql://localhost:3306/APEXLEGENDS
    username: root
    password: apex
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create-drop

dbcp2.jdbc:
  url: jdbc:mysql://localhost:3306/APEXLEGENDS
  username: root
  password: apex
  driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE